spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/onlinebookstore
    username: postgres
    password: 5253228432
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

#    properties:
#      hibernate:
#        format_sql: true
#        default-schema: kil


springdoc:
  swagger-ui:
    path: /swagger-ui.html
connection:
  liquibase:
    enabled: true

